export const users = [
    {
      ID: 1,
      ProfilePhoto: 'https://example.com/images/user1.jpg',
      FirstName: 'John',
      LastName: 'Doe',
      Age: 30,
      Education: "Bachelor's in Computer Science",
      NationalID: '123456789',
      BirthDate: '1993-05-15',
    },
    {
      ID: 2,
      ProfilePhoto: 'https://example.com/images/user2.jpg',
      FirstName: 'Jane',
      LastName: 'Smith',
      Age: 28,
      Education: "Master's in Business Administration",
      NationalID: '987654321',
      BirthDate: '1995-03-22',
    },
    {
      ID: 3,
      ProfilePhoto: 'https://example.com/images/user3.jpg',
      FirstName: 'Alice',
      LastName: 'Johnson',
      Age: 35,
      Education: 'PhD in Physics',
      NationalID: '456123789',
      BirthDate: '1988-12-10',
    },
    {
      ID: 4,
      ProfilePhoto: 'https://example.com/images/user4.jpg',
      FirstName: 'Bob',
      LastName: 'Williams',
      Age: 40,
      Education: 'High School Diploma',
      NationalID: '789123456',
      BirthDate: '1983-07-19',
    },
    {
      ID: 5,
      ProfilePhoto: 'https://example.com/images/user5.jpg',
      FirstName: 'Charlie',
      LastName: 'Brown',
      Age: 25,
      Education: 'Associate Degree in Arts',
      NationalID: '321654987',
      BirthDate: '1998-09-05',
    },
    {
      ID: 6,
      ProfilePhoto: 'https://example.com/images/user6.jpg',
      FirstName: 'Eve',
      LastName: 'Davis',
      Age: 29,
      Education: "Bachelor's in Marketing",
      NationalID: '654321987',
      BirthDate: '1994-11-18',
    },
    {
      ID: 7,
      ProfilePhoto: 'https://example.com/images/user7.jpg',
      FirstName: 'David',
      LastName: 'Miller',
      Age: 33,
      Education: "Master's in Finance",
      NationalID: '987654123',
      BirthDate: '1990-01-25',
    },
    {
      ID: 8,
      ProfilePhoto: 'https://example.com/images/user8.jpg',
      FirstName: 'Olivia',
      LastName: 'Wilson',
      Age: 27,
      Education: "Bachelor's in Psychology",
      NationalID: '456789321',
      BirthDate: '1996-06-02',
    },
    {
      ID: 9,
      ProfilePhoto: 'https://example.com/images/user9.jpg',
      FirstName: 'Sophia',
      LastName: 'Moore',
      Age: 32,
      Education: "Master's in Engineering",
      NationalID: '234567890',
      BirthDate: '1991-02-11',
    },
    {
      ID: 10,
      ProfilePhoto: 'https://example.com/images/user10.jpg',
      FirstName: 'Michael',
      LastName: 'Taylor',
      Age: 38,
      Education: "Master's in Medicine",
      NationalID: '678901234',
      BirthDate: '1985-04-17',
    },
    {
      ID: 11,
      ProfilePhoto: 'https://example.com/images/user11.jpg',
      FirstName: 'Isabella',
      LastName: 'Anderson',
      Age: 26,
      Education: "Bachelor's in Law",
      NationalID: '987654312',
      BirthDate: '1997-08-03',
    },
    {
      ID: 12,
      ProfilePhoto: 'https://example.com/images/user12.jpg',
      FirstName: 'Lucas',
      LastName: 'Thomas',
      Age: 41,
      Education: 'PhD in Computer Science',
      NationalID: '321987654',
      BirthDate: '1982-09-25',
    },
    {
      ID: 13,
      ProfilePhoto: 'https://example.com/images/user13.jpg',
      FirstName: 'Mia',
      LastName: 'Jackson',
      Age: 24,
      Education: "Bachelor's in Business Management",
      NationalID: '135792468',
      BirthDate: '1999-02-15',
    },
    {
      ID: 14,
      ProfilePhoto: 'https://example.com/images/user14.jpg',
      FirstName: 'Daniel',
      LastName: 'White',
      Age: 36,
      Education: "Master's in Data Science",
      NationalID: '543216789',
      BirthDate: '1987-12-30',
    },
    {
      ID: 15,
      ProfilePhoto: 'https://example.com/images/user15.jpg',
      FirstName: 'Amelia',
      LastName: 'Harris',
      Age: 31,
      Education: "Bachelor's in Graphic Design",
      NationalID: '654987321',
      BirthDate: '1992-07-10',
    },
    {
      ID: 16,
      ProfilePhoto: 'https://example.com/images/user16.jpg',
      FirstName: 'Benjamin',
      LastName: 'Clark',
      Age: 45,
      Education: 'PhD in Philosophy',
      NationalID: '198745632',
      BirthDate: '1978-03-14',
    },
    {
      ID: 17,
      ProfilePhoto: 'https://example.com/images/user17.jpg',
      FirstName: 'Ella',
      LastName: 'Rodriguez',
      Age: 22,
      Education: 'Associate Degree in Science',
      NationalID: '198765432',
      BirthDate: '2001-04-21',
    },
    {
      ID: 18,
      ProfilePhoto: 'https://example.com/images/user18.jpg',
      FirstName: 'Samuel',
      LastName: 'Martinez',
      Age: 39,
      Education: "Master's in Architecture",
      NationalID: '345678901',
      BirthDate: '1984-01-06',
    },
    {
      ID: 19,
      ProfilePhoto: 'https://example.com/images/user19.jpg',
      FirstName: 'Lily',
      LastName: 'Gonzalez',
      Age: 27,
      Education: "Bachelor's in Nursing",
      NationalID: '765432109',
      BirthDate: '1996-12-05',
    },
    {
      ID: 20,
      ProfilePhoto: 'https://example.com/images/user20.jpg',
      FirstName: 'Henry',
      LastName: 'Perez',
      Age: 33,
      Education: "Master's in Marketing",
      NationalID: '543217890',
      BirthDate: '1990-08-10',
    },
    {
      ID: 21,
      ProfilePhoto: 'https://example.com/images/user21.jpg',
      FirstName: 'Zoe',
      LastName: 'Wilson',
      Age: 32,
      Education: 'PhD in History',
      NationalID: '132435465',
      BirthDate: '1991-11-22',
    },
    {
      ID: 22,
      ProfilePhoto: 'https://example.com/images/user22.jpg',
      FirstName: 'Chloe',
      LastName: 'Lee',
      Age: 28,
      Education: "Bachelor's in Computer Engineering",
      NationalID: '765432908',
      BirthDate: '1995-05-16',
    },
    {
      ID: 23,
      ProfilePhoto: 'https://example.com/images/user23.jpg',
      FirstName: 'Nathan',
      LastName: 'Young',
      Age: 29,
      Education: "Bachelor's in Physics",
      NationalID: '132465798',
      BirthDate: '1994-02-20',
    },
    {
      ID: 24,
      ProfilePhoto: 'https://example.com/images/user24.jpg',
      FirstName: 'Sophia',
      LastName: 'Allen',
      Age: 34,
      Education: "Master's in Environmental Science",
      NationalID: '112233445',
      BirthDate: '1989-10-05',
    },
    {
      ID: 25,
      ProfilePhoto: 'https://example.com/images/user25.jpg',
      FirstName: 'Elijah',
      LastName: 'King',
      Age: 26,
      Education: "Bachelor's in Marketing",
      NationalID: '998877665',
      BirthDate: '1997-03-30',
    },
    {
      ID: 26,
      ProfilePhoto: 'https://example.com/images/user26.jpg',
      FirstName: 'Mason',
      LastName: 'Scott',
      Age: 38,
      Education: "Master's in Cybersecurity",
      NationalID: '221144335',
      BirthDate: '1985-09-12',
    },
    {
      ID: 27,
      ProfilePhoto: 'https://example.com/images/user27.jpg',
      FirstName: 'Amos',
      LastName: 'Terry',
      Age: 41,
      Education: 'PhD in Law',
      NationalID: '448877665',
      BirthDate: '1982-11-15',
    },
    {
      ID: 28,
      ProfilePhoto: 'https://example.com/images/user28.jpg',
      FirstName: 'Liam',
      LastName: 'Roberts',
      Age: 25,
      Education: "Bachelor's in International Relations",
      NationalID: '556677889',
      BirthDate: '1998-04-25',
    },
    {
      ID: 29,
      ProfilePhoto: 'https://example.com/images/user29.jpg',
      FirstName: 'Noah',
      LastName: 'Carter',
      Age: 30,
      Education: "Master's in Psychology",
      NationalID: '667788990',
      BirthDate: '1993-09-17',
    },
    {
      ID: 30,
      ProfilePhoto: 'https://example.com/images/user30.jpg',
      FirstName: 'Ava',
      LastName: 'Mitchell',
      Age: 27,
      Education: "Bachelor's in Journalism",
      NationalID: '887766554',
      BirthDate: '1996-01-29',
    },
  ]